//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 2.0.5.0
// 
namespace LiveSearch_Parks.MSNSearchService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex", ConfigurationName="MSNSearchService.MSNSearchPortType")]
    public interface MSNSearchPortType {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://schemas.microsoft.com/MSNSearch/2005/09/fex/Search", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginSearch(LiveSearch_Parks.MSNSearchService.SearchRequest Request, System.AsyncCallback callback, object asyncState);
        
        [return: System.ServiceModel.MessageParameterAttribute(Name="Response")]
        LiveSearch_Parks.MSNSearchService.SearchResponse EndSearch(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    public partial class SearchRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string appIDField;
        
        private string queryField;
        
        private string cultureInfoField;
        
        private SafeSearchOptions safeSearchField;
        
        private SearchFlags flagsField;
        
        private Location locationField;
        
        private SourceRequest[] requestsField;
        
        public SearchRequest() {
            this.safeSearchField = SafeSearchOptions.Moderate;
            this.flagsField = SearchFlags.None;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AppID {
            get {
                return this.appIDField;
            }
            set {
                this.appIDField = value;
                this.RaisePropertyChanged("AppID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
                this.RaisePropertyChanged("Query");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CultureInfo {
            get {
                return this.cultureInfoField;
            }
            set {
                this.cultureInfoField = value;
                this.RaisePropertyChanged("CultureInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public SafeSearchOptions SafeSearch {
            get {
                return this.safeSearchField;
            }
            set {
                this.safeSearchField = value;
                this.RaisePropertyChanged("SafeSearch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public SearchFlags Flags {
            get {
                return this.flagsField;
            }
            set {
                this.flagsField = value;
                this.RaisePropertyChanged("Flags");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Location Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SourceRequest[] Requests {
            get {
                return this.requestsField;
            }
            set {
                this.requestsField = value;
                this.RaisePropertyChanged("Requests");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    public enum SafeSearchOptions {
        
        /// <remarks/>
        Moderate,
        
        /// <remarks/>
        Strict,
        
        /// <remarks/>
        Off,
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    public enum SearchFlags {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        MarkQueryWords = 2,
        
        /// <remarks/>
        DisableSpellCorrectForSpecialWords = 4,
        
        /// <remarks/>
        DisableHostCollapsing = 8,
        
        /// <remarks/>
        DisableLocationDetection = 16,
        
        /// <remarks/>
        DisableWebQueryAlteration = 32,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    public partial class Location : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double latitudeField;
        
        private double longitudeField;
        
        private double radiusField;
        
        public Location() {
            this.radiusField = 5;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(5)]
        public double Radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
                this.RaisePropertyChanged("Radius");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    public partial class MotionThumbnail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uRLField;
        
        private string formatField;
        
        private int runTimeField;
        
        private bool runTimeFieldSpecified;
        
        private int widthField;
        
        private bool widthFieldSpecified;
        
        private int heightField;
        
        private bool heightFieldSpecified;
        
        private int fileSizeField;
        
        private bool fileSizeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
                this.RaisePropertyChanged("Format");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int RunTime {
            get {
                return this.runTimeField;
            }
            set {
                this.runTimeField = value;
                this.RaisePropertyChanged("RunTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RunTimeSpecified {
            get {
                return this.runTimeFieldSpecified;
            }
            set {
                this.runTimeFieldSpecified = value;
                this.RaisePropertyChanged("RunTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("Width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WidthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
                this.RaisePropertyChanged("WidthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("Height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
                this.RaisePropertyChanged("HeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int FileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
                this.RaisePropertyChanged("FileSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileSizeSpecified {
            get {
                return this.fileSizeFieldSpecified;
            }
            set {
                this.fileSizeFieldSpecified = value;
                this.RaisePropertyChanged("FileSizeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    public partial class StaticThumbnail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uRLField;
        
        private string formatField;
        
        private int widthField;
        
        private bool widthFieldSpecified;
        
        private int heightField;
        
        private bool heightFieldSpecified;
        
        private int fileSizeField;
        
        private bool fileSizeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
                this.RaisePropertyChanged("Format");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("Width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WidthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
                this.RaisePropertyChanged("WidthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("Height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
                this.RaisePropertyChanged("HeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int FileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
                this.RaisePropertyChanged("FileSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileSizeSpecified {
            get {
                return this.fileSizeFieldSpecified;
            }
            set {
                this.fileSizeFieldSpecified = value;
                this.RaisePropertyChanged("FileSizeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    public partial class Video : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string playUrlField;
        
        private string sourceTitleField;
        
        private string formatField;
        
        private int runTimeField;
        
        private bool runTimeFieldSpecified;
        
        private int widthField;
        
        private bool widthFieldSpecified;
        
        private int heightField;
        
        private bool heightFieldSpecified;
        
        private int fileSizeField;
        
        private bool fileSizeFieldSpecified;
        
        private StaticThumbnail staticThumbnailField;
        
        private MotionThumbnail motionThumbnailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PlayUrl {
            get {
                return this.playUrlField;
            }
            set {
                this.playUrlField = value;
                this.RaisePropertyChanged("PlayUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SourceTitle {
            get {
                return this.sourceTitleField;
            }
            set {
                this.sourceTitleField = value;
                this.RaisePropertyChanged("SourceTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
                this.RaisePropertyChanged("Format");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int RunTime {
            get {
                return this.runTimeField;
            }
            set {
                this.runTimeField = value;
                this.RaisePropertyChanged("RunTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RunTimeSpecified {
            get {
                return this.runTimeFieldSpecified;
            }
            set {
                this.runTimeFieldSpecified = value;
                this.RaisePropertyChanged("RunTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("Width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WidthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
                this.RaisePropertyChanged("WidthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("Height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
                this.RaisePropertyChanged("HeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int FileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
                this.RaisePropertyChanged("FileSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileSizeSpecified {
            get {
                return this.fileSizeFieldSpecified;
            }
            set {
                this.fileSizeFieldSpecified = value;
                this.RaisePropertyChanged("FileSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public StaticThumbnail StaticThumbnail {
            get {
                return this.staticThumbnailField;
            }
            set {
                this.staticThumbnailField = value;
                this.RaisePropertyChanged("StaticThumbnail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public MotionThumbnail MotionThumbnail {
            get {
                return this.motionThumbnailField;
            }
            set {
                this.motionThumbnailField = value;
                this.RaisePropertyChanged("MotionThumbnail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    public partial class Image : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string imageURLField;
        
        private int imageWidthField;
        
        private bool imageWidthFieldSpecified;
        
        private int imageHeightField;
        
        private bool imageHeightFieldSpecified;
        
        private int imageFileSizeField;
        
        private bool imageFileSizeFieldSpecified;
        
        private string thumbnailURLField;
        
        private int thumbnailWidthField;
        
        private bool thumbnailWidthFieldSpecified;
        
        private int thumbnailHeightField;
        
        private bool thumbnailHeightFieldSpecified;
        
        private int thumbnailFileSizeField;
        
        private bool thumbnailFileSizeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ImageURL {
            get {
                return this.imageURLField;
            }
            set {
                this.imageURLField = value;
                this.RaisePropertyChanged("ImageURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ImageWidth {
            get {
                return this.imageWidthField;
            }
            set {
                this.imageWidthField = value;
                this.RaisePropertyChanged("ImageWidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ImageWidthSpecified {
            get {
                return this.imageWidthFieldSpecified;
            }
            set {
                this.imageWidthFieldSpecified = value;
                this.RaisePropertyChanged("ImageWidthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ImageHeight {
            get {
                return this.imageHeightField;
            }
            set {
                this.imageHeightField = value;
                this.RaisePropertyChanged("ImageHeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ImageHeightSpecified {
            get {
                return this.imageHeightFieldSpecified;
            }
            set {
                this.imageHeightFieldSpecified = value;
                this.RaisePropertyChanged("ImageHeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ImageFileSize {
            get {
                return this.imageFileSizeField;
            }
            set {
                this.imageFileSizeField = value;
                this.RaisePropertyChanged("ImageFileSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ImageFileSizeSpecified {
            get {
                return this.imageFileSizeFieldSpecified;
            }
            set {
                this.imageFileSizeFieldSpecified = value;
                this.RaisePropertyChanged("ImageFileSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ThumbnailURL {
            get {
                return this.thumbnailURLField;
            }
            set {
                this.thumbnailURLField = value;
                this.RaisePropertyChanged("ThumbnailURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ThumbnailWidth {
            get {
                return this.thumbnailWidthField;
            }
            set {
                this.thumbnailWidthField = value;
                this.RaisePropertyChanged("ThumbnailWidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ThumbnailWidthSpecified {
            get {
                return this.thumbnailWidthFieldSpecified;
            }
            set {
                this.thumbnailWidthFieldSpecified = value;
                this.RaisePropertyChanged("ThumbnailWidthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int ThumbnailHeight {
            get {
                return this.thumbnailHeightField;
            }
            set {
                this.thumbnailHeightField = value;
                this.RaisePropertyChanged("ThumbnailHeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ThumbnailHeightSpecified {
            get {
                return this.thumbnailHeightFieldSpecified;
            }
            set {
                this.thumbnailHeightFieldSpecified = value;
                this.RaisePropertyChanged("ThumbnailHeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int ThumbnailFileSize {
            get {
                return this.thumbnailFileSizeField;
            }
            set {
                this.thumbnailFileSizeField = value;
                this.RaisePropertyChanged("ThumbnailFileSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ThumbnailFileSizeSpecified {
            get {
                return this.thumbnailFileSizeFieldSpecified;
            }
            set {
                this.thumbnailFileSizeFieldSpecified = value;
                this.RaisePropertyChanged("ThumbnailFileSizeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    public partial class SearchTag : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressLineField;
        
        private string primaryCityField;
        
        private string secondaryCityField;
        
        private string subdivisionField;
        
        private string postalCodeField;
        
        private string countryRegionField;
        
        private string formattedAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AddressLine {
            get {
                return this.addressLineField;
            }
            set {
                this.addressLineField = value;
                this.RaisePropertyChanged("AddressLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PrimaryCity {
            get {
                return this.primaryCityField;
            }
            set {
                this.primaryCityField = value;
                this.RaisePropertyChanged("PrimaryCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SecondaryCity {
            get {
                return this.secondaryCityField;
            }
            set {
                this.secondaryCityField = value;
                this.RaisePropertyChanged("SecondaryCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Subdivision {
            get {
                return this.subdivisionField;
            }
            set {
                this.subdivisionField = value;
                this.RaisePropertyChanged("Subdivision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CountryRegion {
            get {
                return this.countryRegionField;
            }
            set {
                this.countryRegionField = value;
                this.RaisePropertyChanged("CountryRegion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FormattedAddress {
            get {
                return this.formattedAddressField;
            }
            set {
                this.formattedAddressField = value;
                this.RaisePropertyChanged("FormattedAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    public partial class DateTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int yearField;
        
        private int monthField;
        
        private int dayField;
        
        private int hourField;
        
        private int minuteField;
        
        private int secondField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
                this.RaisePropertyChanged("Month");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
                this.RaisePropertyChanged("Day");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Hour {
            get {
                return this.hourField;
            }
            set {
                this.hourField = value;
                this.RaisePropertyChanged("Hour");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Minute {
            get {
                return this.minuteField;
            }
            set {
                this.minuteField = value;
                this.RaisePropertyChanged("Minute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Second {
            get {
                return this.secondField;
            }
            set {
                this.secondField = value;
                this.RaisePropertyChanged("Second");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    public partial class Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string titleField;
        
        private string descriptionField;
        
        private string urlField;
        
        private string displayUrlField;
        
        private string cacheUrlField;
        
        private string sourceField;
        
        private string searchTagsField;
        
        private string phoneField;
        
        private DateTime dateTimeField;
        
        private Address addressField;
        
        private Location locationField;
        
        private SearchTag[] searchTagsArrayField;
        
        private string summaryField;
        
        private string resultTypeField;
        
        private Image imageField;
        
        private Video videoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("Url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DisplayUrl {
            get {
                return this.displayUrlField;
            }
            set {
                this.displayUrlField = value;
                this.RaisePropertyChanged("DisplayUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CacheUrl {
            get {
                return this.cacheUrlField;
            }
            set {
                this.cacheUrlField = value;
                this.RaisePropertyChanged("CacheUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SearchTags {
            get {
                return this.searchTagsField;
            }
            set {
                this.searchTagsField = value;
                this.RaisePropertyChanged("SearchTags");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public DateTime DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
                this.RaisePropertyChanged("DateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public Location Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SearchTag[] SearchTagsArray {
            get {
                return this.searchTagsArrayField;
            }
            set {
                this.searchTagsArrayField = value;
                this.RaisePropertyChanged("SearchTagsArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
                this.RaisePropertyChanged("Summary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ResultType {
            get {
                return this.resultTypeField;
            }
            set {
                this.resultTypeField = value;
                this.RaisePropertyChanged("ResultType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public Image Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("Image");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public Video Video {
            get {
                return this.videoField;
            }
            set {
                this.videoField = value;
                this.RaisePropertyChanged("Video");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    public partial class SourceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SourceType sourceField;
        
        private int offsetField;
        
        private int totalField;
        
        private string recourseQueryField;
        
        private Result[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SourceType Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
                this.RaisePropertyChanged("Offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RecourseQuery {
            get {
                return this.recourseQueryField;
            }
            set {
                this.recourseQueryField = value;
                this.RaisePropertyChanged("RecourseQuery");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Result[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("Results");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    public enum SourceType {
        
        /// <remarks/>
        Web,
        
        /// <remarks/>
        News,
        
        /// <remarks/>
        Ads,
        
        /// <remarks/>
        InlineAnswers,
        
        /// <remarks/>
        PhoneBook,
        
        /// <remarks/>
        WordBreaker,
        
        /// <remarks/>
        Spelling,
        
        /// <remarks/>
        QueryLocation,
        
        /// <remarks/>
        Image,
        
        /// <remarks/>
        Video,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    public partial class SearchResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SourceResponse[] responsesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SourceResponse[] Responses {
            get {
                return this.responsesField;
            }
            set {
                this.responsesField = value;
                this.RaisePropertyChanged("Responses");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    public partial class SourceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SourceType sourceField;
        
        private int offsetField;
        
        private int countField;
        
        private string fileTypeField;
        
        private SortByType sortByField;
        
        private ResultFieldMask resultFieldsField;
        
        private string[] searchTagFiltersField;
        
        public SourceRequest() {
            this.sourceField = SourceType.Web;
            this.offsetField = 0;
            this.countField = 10;
            this.sortByField = SortByType.Default;
            this.resultFieldsField = ((ResultFieldMask.Title | ResultFieldMask.Description) 
                        | ResultFieldMask.Url);
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SourceType Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
                this.RaisePropertyChanged("Offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("Count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
                this.RaisePropertyChanged("FileType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DefaultValueAttribute(SortByType.Default)]
        public SortByType SortBy {
            get {
                return this.sortByField;
            }
            set {
                this.sortByField = value;
                this.RaisePropertyChanged("SortBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public ResultFieldMask ResultFields {
            get {
                return this.resultFieldsField;
            }
            set {
                this.resultFieldsField = value;
                this.RaisePropertyChanged("ResultFields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public string[] SearchTagFilters {
            get {
                return this.searchTagFiltersField;
            }
            set {
                this.searchTagFiltersField = value;
                this.RaisePropertyChanged("SearchTagFilters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    public enum SortByType {
        
        /// <remarks/>
        Default = 1,
        
        /// <remarks/>
        Relevance = 2,
        
        /// <remarks/>
        Distance = 4,
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/MSNSearch/2005/09/fex")]
    public enum ResultFieldMask {
        
        /// <remarks/>
        All = 1,
        
        /// <remarks/>
        Title = 2,
        
        /// <remarks/>
        Description = 4,
        
        /// <remarks/>
        Url = 8,
        
        /// <remarks/>
        DisplayUrl = 16,
        
        /// <remarks/>
        CacheUrl = 32,
        
        /// <remarks/>
        Source = 64,
        
        /// <remarks/>
        SearchTags = 128,
        
        /// <remarks/>
        Phone = 256,
        
        /// <remarks/>
        DateTime = 512,
        
        /// <remarks/>
        Address = 1024,
        
        /// <remarks/>
        Location = 2048,
        
        /// <remarks/>
        SearchTagsArray = 4096,
        
        /// <remarks/>
        Summary = 8192,
        
        /// <remarks/>
        ResultType = 16384,
        
        /// <remarks/>
        Image = 32768,
        
        /// <remarks/>
        Video = 65536,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface MSNSearchPortTypeChannel : LiveSearch_Parks.MSNSearchService.MSNSearchPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LiveSearch_Parks.MSNSearchService.SearchResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LiveSearch_Parks.MSNSearchService.SearchResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MSNSearchPortTypeClient : System.ServiceModel.ClientBase<LiveSearch_Parks.MSNSearchService.MSNSearchPortType>, LiveSearch_Parks.MSNSearchService.MSNSearchPortType {
        
        private BeginOperationDelegate onBeginSearchDelegate;
        
        private EndOperationDelegate onEndSearchDelegate;
        
        private System.Threading.SendOrPostCallback onSearchCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public MSNSearchPortTypeClient() {
        }
        
        public MSNSearchPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MSNSearchPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MSNSearchPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MSNSearchPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<SearchCompletedEventArgs> SearchCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LiveSearch_Parks.MSNSearchService.MSNSearchPortType.BeginSearch(LiveSearch_Parks.MSNSearchService.SearchRequest Request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearch(Request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LiveSearch_Parks.MSNSearchService.SearchResponse LiveSearch_Parks.MSNSearchService.MSNSearchPortType.EndSearch(System.IAsyncResult result) {
            return base.Channel.EndSearch(result);
        }
        
        private System.IAsyncResult OnBeginSearch(object[] inValues, System.AsyncCallback callback, object asyncState) {
            LiveSearch_Parks.MSNSearchService.SearchRequest Request = ((LiveSearch_Parks.MSNSearchService.SearchRequest)(inValues[0]));
            return ((LiveSearch_Parks.MSNSearchService.MSNSearchPortType)(this)).BeginSearch(Request, callback, asyncState);
        }
        
        private object[] OnEndSearch(System.IAsyncResult result) {
            LiveSearch_Parks.MSNSearchService.SearchResponse retVal = ((LiveSearch_Parks.MSNSearchService.MSNSearchPortType)(this)).EndSearch(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSearchCompleted(object state) {
            if ((this.SearchCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchCompleted(this, new SearchCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SearchAsync(LiveSearch_Parks.MSNSearchService.SearchRequest Request) {
            this.SearchAsync(Request, null);
        }
        
        public void SearchAsync(LiveSearch_Parks.MSNSearchService.SearchRequest Request, object userState) {
            if ((this.onBeginSearchDelegate == null)) {
                this.onBeginSearchDelegate = new BeginOperationDelegate(this.OnBeginSearch);
            }
            if ((this.onEndSearchDelegate == null)) {
                this.onEndSearchDelegate = new EndOperationDelegate(this.OnEndSearch);
            }
            if ((this.onSearchCompletedDelegate == null)) {
                this.onSearchCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchCompleted);
            }
            base.InvokeAsync(this.onBeginSearchDelegate, new object[] {
                        Request}, this.onEndSearchDelegate, this.onSearchCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override LiveSearch_Parks.MSNSearchService.MSNSearchPortType CreateChannel() {
            return new MSNSearchPortTypeClientChannel(this);
        }
        
        private class MSNSearchPortTypeClientChannel : ChannelBase<LiveSearch_Parks.MSNSearchService.MSNSearchPortType>, LiveSearch_Parks.MSNSearchService.MSNSearchPortType {
            
            public MSNSearchPortTypeClientChannel(System.ServiceModel.ClientBase<LiveSearch_Parks.MSNSearchService.MSNSearchPortType> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginSearch(LiveSearch_Parks.MSNSearchService.SearchRequest Request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Request;
                System.IAsyncResult _result = base.BeginInvoke("Search", _args, callback, asyncState);
                return _result;
            }
            
            public LiveSearch_Parks.MSNSearchService.SearchResponse EndSearch(System.IAsyncResult result) {
                object[] _args = new object[0];
                LiveSearch_Parks.MSNSearchService.SearchResponse _result = ((LiveSearch_Parks.MSNSearchService.SearchResponse)(base.EndInvoke("Search", _args, result)));
                return _result;
            }
        }
    }
}
